### PR TITLE
fix: also update when inputRev changes

### LINKED ISSUE #119: `lake update` does not pick up updates from transitive dependencies
For example `mathlib3port` depends on `lean3port` which depends on `mathlib4`.  But running `lake update` in `mathlib3port` does not pick up the new `mathlib4` version when `lean3port` updates its dependency.

We touched on this in another issue, but it's still an issue in the latest release. See https://github.com/leanprover/lake/issues/70#issuecomment-1215033902:

> My simplest solution to all of this is to append dependency's manifests to the top-level package's with their entries mark `inherited` and not update such dependencies during `lake update`.

"... but instead replace them with the current entry from the dependency's manifest."  Otherwise sounds good to me.

### PR DESCRIPTION
**Pull request by gebner**
It turns out that #119 already worked in some cases.  Namely `lake update` would pick up changes in transitive dependencies, but only if the `inputRev` stayed the same.  If the direct dependency switched to another branch of the transitive dependency, then `lake update` would not pick up the new revision.

This PR removes the `inputRev` check and adds a test for this issue.

Fixes #119.

### CODE REVIEW

**Comment by tydeu** [comment]
@gebner Thanks for the PR, especially the updated test! 😄

However, this does not actually fix the underlying issue.  First, removing the check does not result in Lake copying the entry from a transitive dependency. Rather, it results in it updating the specified dependency to its latest version (a la `lake update`). Second, the check was there for a reason. Without it, transitive dependencies are updated on every `lake build` (not just `lake update`), which is not ideal. (Though, upon reflection, the check does fully achieve what it was meant to do either.)

**Comment by gebner** [comment]
Oh that is indeed an issue.  I think I got confused by the two meanings of `shouldUpdate` here (are we inside `lake update` vs. should we do a `git pull`).  Maybe it would be best to separate the two functions.

I've updated the test to include the issue you've mentioned.

**Comment by tydeu** [comment]
>  I think I got confused by the two meanings of `shouldUpdate` here (are we inside `lake update` vs. should we do a `git pull`). Maybe it would be best to separate the two functions.

For reference, `shouldUpdate` always means "should we do a `git pull`" -- there is no setting for "are we inside a `lake update`". It is just that `lake update` sets `shouldUpdate` since it wants to do a git pull (because that is what `lake update` is for).

**Comment by gebner** [comment]
Superseded by #138.

**Pull request closed without merging**
