### PR TITLE
test: use `$LAKE` everywhere

### PR DESCRIPTION
**Pull request by Kha**

### CODE REVIEW

**Comment by Kha** [comment]
Eek, looks like `$(PWD)` is incompatible with `make -C`

**Comment by tydeu** [comment]
I also run examples shell scripts directly while developing / testing, so those scripts would still need to default to the normal path if no `LAKE` variable is set.

**Comment by Kha** [comment]
Soo, change it to `${LAKE:-../../build/bin/lake}` etc.? The alternative would be to just rely on PATH and use `lake` everywhere, don't know if that is compatible with your development workflow.

**Comment by tydeu** [comment]
> Soo, should I change it to `${LAKE:-../../build/bin/lake}` etc.?

Yes, that should work for me.

**Comment by tydeu** [comment]
Looks good! Only one more suggestion: In the Makefile, could you just use `LAKE ?= ../build/bin/lake` (and `${LAKE}`) in the targe to allow `LAKE` to be overwrite by environment variables?

**Comment by Kha** [comment]
That is already the case. Defaulting `LAKE` to a relative path like that will break any `${LAKE:-...` references in nested directories.

**Comment by tydeu** [comment]
But wouldn't that only apply to `check-lake` command? A `LAKE ?= ../build/bin/lake` command in the Makefile doesn't set an environment variable just a variable for that Makefile right?

**Comment by tydeu** [comment]
True, though it would be more future-proof. That is, it would be useful if there eventually are more targets in the Makefile that use `LAKE` (one wouldn't have to replicate the default at each use).

**Comment by tydeu** [comment]
Thanks! Looks great! Also, sorry about have such an extended (and somewhat trivial) back and forth (which was probably more time consuming than the actual changes).

**Pull request merged**
