### PR TITLE
chore: bump for lean4#1384

### PR DESCRIPTION
**Pull request by digama0**
This adds support for leanprover/lean4#1384 . Because of the submodule situation I think leanprover/lean4#1384 can't compile until it can see this commit, so if someone could create a branch for this commit upstream that would be helpful.

### CODE REVIEW

**Comment by Kha** [comment]
We should definitely keep the branches in this repo where we have control over them (not being deleted). I created the branch.

**Comment by tydeu** [comment]
@digama0 What version of Lean is this suppose to work on? I tried it on the 08-01 nightly, but it didn't seem to like it. I would really appreciate it if you could update the `lean-toolchain` file in this branch (e.g., in a separate commit) to the version this works on and get the tests passing.

**Comment by digama0** [comment]
The later changes to the PR made this change unnecessary. The `decl_name%` is being inserted by an autoparam now; no code changes are required to work with [#1384](https://github.com/leanprover/lean4/pull/1384).

**Comment by tydeu** [comment]
Ah, okay, thanks! 👍

**Pull request closed without merging**
