### PR TITLE
chore: Min/Max typeclasses

### PR DESCRIPTION
**Pull request by gebner**
Companion PR to https://github.com/leanprover/lean4/pull/1765

### CODE REVIEW

**Comment by tydeu** [comment]
@gebner Please do not combine the Lean version update with the original edit commit. We need to keep the original commit in `master`'s history so that the commits in Lake distributed with Lean also exist in the Lake repository.

**Comment by gebner** [comment]
CI obviously does not pass without the version upgrade.  What do you suggest I should do instead?

**Comment by tydeu** [comment]
@gebner There should be two separate commits: the edit (the exact same commit from the Lake submodule) and then the version update  (If you look at the history of master you can see how I have been doing it.)

**Comment by gebner** [comment]
Okay, got it!

**Pull request merged**
